### ISSUE TITLE
Subscribe button disoriented

### ISSUE THREAD

**Issue by amir-rahnama** [cbanowsky/crush#2]
![screen shot 2015-05-07 at 21 49 02](https://cloud.githubusercontent.com/assets/6009583/7524558/1fa6902a-f503-11e4-8f65-c0bb30760e0b.png)

**Comment by cbanowsky** [comment]
Will have this resolved for you

**Comment by cbanowsky** [comment]
When did you clone this repo? I am unable to reproduce your error.
